import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'
export default function Home() {
   const router = useRouter()
   const {slug}  = router.query
  return (
    <div className={styles.container}>
      <Head>
        <title>Logado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <p>Logado</p>
        <p>Token:{slug}</p>

      </main>
    </div>
  )
}
