import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {FcGoogle} from 'react-icons/fc'
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
    <h1>Logar com a conta google</h1>
        <Link href="/api/google">
     <a  className={styles.google} ><FcGoogle size={24}/> <p>Google</p></a>
        </Link>
        </div>

      </main>
    </div>
  )
}
